pub const MAIN: &str = concat!(
    "**🤖 Construct Help**\n",
    "Use: .command _args_\n\n",
    "**📂 Project**\n",
    "* new [name]: Reset/create project\n",
    "* project [path]: Set project directory\n",
    "* list: List projects\n",
    "* task [desc]: Start a new task\n",
    "* modify [desc]: Modify current task\n",
    "* start: Start/resume tasks\n",
    "* stop: Stop tasks\n",
    "* cleanup: Clean room state (admin only)\n\n",
    "**🐙 Git**\n",
    "* changes\n",
    "* commit [msg]\n",
    "* discard\n\n",
    "**🔨 Build**\n",
    "* check\n",
    "* build\n",
    "* deploy\n\n",
    "**⚡ Misc**\n",
    "* , [cmd]: Terminal command\n",
    "* agents: list agents\n",
    "* agent [id]: set agent\n",
    "* models: list models\n",
    "* model [id]: set model\n",
    "* ask [msg]: Chat with agent\n",
    "* set [k] [v]\n",
    "* read [files]\n",
    "* status\n"
);
