#[derive(Debug)]
pub struct HelpStrings {
    pub main: &'static str,
}

#[derive(Debug)]
pub struct WizardStrings {
    pub project_name: &'static str,
    pub project_type: &'static str,
    pub stack: &'static str,
    pub task_description: &'static str,
    pub cancelled: &'static str,
}

#[derive(Debug)]
pub struct PromptStrings {
    pub system: &'static str,
    pub task_instructions: &'static str,
    pub task_format: &'static str,
    pub new_project_instructions: &'static str,
    pub new_project_format: &'static str,
    pub modify_plan: &'static str,
    pub task_requirements_prompt: &'static str,
    pub new_project_prompt: &'static str,
    pub roadmap_template: &'static str,
    pub changelog_template: &'static str,
    pub roadmap_context: &'static str,
    pub initial_history_context: &'static str,

    pub interactive_turn: &'static str,
}

#[derive(Debug)]
pub struct MessageStrings {
    pub status_header: &'static str,
    pub model_set: &'static str,
    pub model_reset: &'static str,
    pub invalid_model: &'static str,
    pub no_projects_found: &'static str,
    pub available_projects_header: &'static str,
    pub invalid_project_name: &'static str,
    pub admin_permission_denied: &'static str,
    pub directory_changed: &'static str,
    pub access_denied_sandbox: &'static str,
    pub directory_not_found: &'static str,
    pub command_no_output: &'static str,

    pub write_plan_error: &'static str,
    pub write_tasks_error: &'static str,
    pub feedback_modification: &'static str,
    pub failed_modify: &'static str,
    pub plan_updated: &'static str,
    pub limit_reached: &'static str,
    pub stop_requested: &'static str,

    pub execution_complete: &'static str,
    pub agent_says: &'static str,
    pub agent_output: &'static str,

    pub stop_request_wait: &'static str,
    pub plan_approved: &'static str,
    pub no_task_approve: &'static str,
    pub resuming_execution: &'static str,
    pub no_history_continue: &'static str,

    pub please_commit_msg: &'static str,
    pub committed_msg: &'static str,
    pub changes_discarded: &'static str,
    pub checking_msg: &'static str,
    pub check_result: &'static str,
    pub building_msg: &'static str,
    pub build_result: &'static str,
    pub deploying_msg: &'static str,
    pub deploy_result: &'static str,
    pub code_block_output: &'static str,
    pub command_blocked: &'static str,
    pub command_ask: &'static str,
    pub command_not_allowed: &'static str,
    pub command_unknown: &'static str,
    pub command_run_failed: &'static str,
    pub shell_command_failed: &'static str,
    pub command_approval_request: &'static str,
    pub command_denied_user: &'static str,
    pub no_pending_command: &'static str,

    pub missing_env_var: &'static str,
    pub gemini_fetch_failed: &'static str,
    pub gemini_api_error: &'static str,
    pub gemini_parse_error: &'static str,
    pub anthropic_fetch_failed: &'static str,
    pub anthropic_api_error: &'static str,
    pub anthropic_parse_error: &'static str,
    pub deepai_request_failed: &'static str,
    pub deepai_api_error: &'static str,
    pub deepai_parse_error: &'static str,
    pub unsupported_provider: &'static str,

    pub no_projects_configured: &'static str,
    pub provide_project_name: &'static str,
    pub project_exists: &'static str,
    pub create_dir_failed: &'static str,
    pub project_created: &'static str,
    pub use_task_to_start: &'static str,

    pub plan_generated: &'static str,
    pub plan_generation_failed: &'static str,
    pub no_active_task_modify: &'static str,
    pub current_changes_header: &'static str,
}

#[derive(Debug)]
pub struct LogStrings {
    pub config_loaded: &'static str,
    pub login_success: &'static str,
    pub setting_display_name: &'static str,
    pub set_display_name_fail: &'static str,
    pub sync_loop_start: &'static str,
    pub sync_loop_fail: &'static str,
    pub shutdown: &'static str,
    pub shutdown_fail: &'static str,
    pub bridge_joining: &'static str,
    pub bridge_join_fail: &'static str,
    pub bridge_join_success: &'static str,
    pub invite_received: &'static str,
    pub join_invite_fail: &'static str,
    pub join_invite_success: &'static str,
}

#[derive(Debug)]
pub struct Strings {
    pub help: HelpStrings,
    pub wizard: WizardStrings,
    pub prompts: PromptStrings,
    pub messages: MessageStrings,
    pub logs: LogStrings,
}

pub static STRINGS: Strings = Strings {
    help: HelpStrings {
        main: concat!(
            "**🤖 Construct Help**\n",
            "Use: .command _args_\n\n",
            "**📂 Project**\n",
            "* new [name]: Reset/create project\n",
            "* project [path]: Set project directory\n",
            "* list: List projects\n",
            "* task [desc]: Start a new task\n",
            "* modify [desc]: Modify current task\n",
            "* start: Start/resume tasks\n",
            "* stop: Stop tasks\n",
            "* cleanup: Clean room state (admin only)\n\n",
            "**🐙 Git**\n",
            "* changes\n",
            "* commit [msg]\n",
            "* discard\n\n",
            "**🔨 Build**\n",
            "* check\n",
            "* build\n",
            "* deploy\n\n",
            "**⚡ Misc**\n",
            "* , [cmd]: Terminal command\n",
            "* agents: list agents\n",
            "* agent [id]: set agent\n",
            "* models: list models\n",
            "* model [id]: set model\n",
            "* ask [msg]: Chat with agent\n",
            "* set [k] [v]\n",
            "* read [files]\n",
            "* status\n"
        ),
    },
    wizard: WizardStrings {
        project_name: "**🚀 New Project Wizard**\n\nPlease enter a **Project Folder Name** (no spaces, e.g., `my-cool-app`):",
        project_type: "**📂 Project Type**\n\n1. Application\n2. Library\n3. CLI Tool\n4. Web Site/App\n\nReply with number or name.",
        stack: "**🛠️ Tech Stack**\n\n1. Rust\n2. Python\n3. TypeScript\n4. Go\n\nReply with number or type custom.",
        task_description: "**📋 New Task Wizard**\n\nEnter requirements as separate messages (each will be a bullet point).\n\nType `.ok` when finished.",
        cancelled: "❌ Wizard cancelled.",
    },
    prompts: PromptStrings {
        system: concat!(
            "# Construct System Prompt\n\n",
            "You are an AI Coding Agent acting as a cooperative collaborator over Matrix.\n",
            "Your goal is to execute code changes to fulfill the user's Task.\n\n",
            "## Rules\n",
            "- Be concise and technical.\n",
            "- Always verify your changes if possible (build/test).\n",
            "- Do not make assumptions; ask for clarification if a task is ambiguous.\n",
            "- Maintain a `tasks.md` file in the project root to track progress. Mark tasks as `[x]` when completed.\n",
            "- Maintain a `walkthrough.md` file to document changes and verification results.\n",
            "- **ERROR HANDLING**: If a command fails (Exit Code != 0), DO NOT retry it blindly.\n",
            "- **TIMEOUTS**: Commands have automatic timeouts to prevent hanging:\n",
            "  - Short commands (ls, cat, grep): 30 seconds\n",
            "  - Medium commands (git, test, build): 120 seconds\n",
            "  - Long commands (cargo build, npm install): 600 seconds\n",
            "  - Timeouts are automatically selected based on command type.\n",
            "  - Long commands (cargo build, npm install): 600 seconds\n",
            "  - If a command times out, break it into smaller steps.\n",
            "- **FEED SYSTEM**: Your progress is tracked in a live feed:\n",
            "  - Active mode: Shows real-time command execution (verbose)\n",
            "  - Squashed mode: Compresses to one-liners when tasks complete\n",
            "  - Final mode: Clean summary when all tasks finish\n",
            "  - Feed is saved as `feed.md` in the project directory\n",
            "- Start the tool output immediately.\n",
            "  - If unclear, ask the user for help.\n",
            "- **VERIFICATION**: Don't trust; verify.\n",
            "  - After running a command that generates files, run `ls` or `cat` to confirm existence.\n",
            "  - Only proceed if expected artifacts are present.\n\n",
            "## Best Practices\n",
            "- **Debugging**: Follow a structured approach: Assess (Context) -> Reproduce (Steps) -> Fix (Minimal) -> Verify (Test).\n",
            "- **Rust Standards**:\n",
            "  - Avoid anti-patterns: `clone()` (borrow instead), `unwrap()` (handle errors), `unsafe` (avoid).\n",
            "  - Treat lints seriously; trace root causes before suppressing.\n",
            "- **Verification**: Run `cargo check` and `cargo test` after every change.\n",
            "- **Completeness**: Do not rely on assumptions. Verify every step.\n",
            "- **Command Line Best Practices**:\n",
            "  - All commands are sandboxed within the project directory for security.\n",
            "  - NO INTERACTIVE TOOLS: DO NOT use `nano`, `vim`, `vi`, `less`, `more`, `top`.\n",
            "  - Use `cat` or `head` to read files.\n",
            "  - Use `ls` to list files.\n",
            "  - Use `cd` to change directories.\n",
            "  - Use `echo 'content' > file` or heredocs for file creation.\n",
            "  - Use `grep` to search.\n",
            "  - File operations are validated for sandbox safety.\n",
            "- **Dependency Management**: ALWAYS use package managers (e.g., `cargo add`, `npm install`, `pip install`) instead of manually editing configuration files (e.g., `Cargo.toml`, `package.json`).\n"
        ),
        task_instructions: concat!(
            "1. Use the 'Project Roadmap' above for understanding the big picture and constraints.\n",
            "2. Your scope is STRICTLY limited to the 'Task' described above. Do NOT try to complete other roadmap items.\n",
            "3. Generate two files:\n",
            "   - `plan.md`: A detailed but CONCISE technical plan for THIS specific task.\n",
            "   - `tasks.md`: A checklist of the subtasks for THIS specific task.\n"
        ),
        task_format: concat!(
            "plan.md\n",
            "```markdown\n",
            "...content...\n",
            "```\n\n",
            "tasks.md\n",
            "```markdown\n",
            "...content...\n",
            "```\n"
        ),
        new_project_instructions: "4. **NEW PROJECT DETECTED**: You MUST also generate `roadmap.md` based on the task requirements to replace the default placeholders.\n",
        new_project_format: concat!(
            "\nroadmap.md\n",
            "```markdown\n",
            "...content...\n",
            "```\n"
        ),
        modify_plan: concat!(
            "{SYSTEM}\n\n",
            "Original Task: {TASK}\n\n",
            "Current Plan:\n",
            "{PLAN}\n\n",
            "Feedback: {FEEDBACK}\n\n",
            "Please update the plan.md based on the feedback.\n\n",
            "IMPORTANT: Return the content of plan.md in a code block.\n"
        ),
        task_requirements_prompt: "Task Requirements:\n\n{}",
        new_project_prompt: "Create a new project named '{NAME}'. \n\nGoal: Comprehensive implementation of the following requirements.\n\nRequirements:\n{REQUIREMENTS}\n\nIMPORTANT: The project directory is ALREADY created. You are ALREADY inside it (`{WORKDIR}`). Do NOT run `mkdir` or `cd`.",
        roadmap_template: "# Roadmap\n\n- [ ] Initial Setup",
        changelog_template: "# Changelog\n\n## 0.1.0\n- Initialized",
        roadmap_context: "\n\n### Project Roadmap (Context Only)\n{}\n",
        initial_history_context: concat!(
            "Task: {TASK}\n\n",
            "Current Plan:\n",
            "{PLAN}\n\n",
            "Tasks Checklist:\n",
            "{TASKS}\n\n",
            "You are executing this plan. We will do this step-by-step.\n\n",
            "You are currently in directory: {WORKDIR}\n"
        ),

        interactive_turn: concat!(
            "{CWD}\n\n",
            "# Project Context\n",
            "## Roadmap\n",
            "{ROADMAP}\n\n",
            "## Tasks\n",
            "{TASKS}\n\n",
            "# Current Status\n",
            "Based on the plan and previous outputs, what is the NEXT single command to run?\n\n",
            "## RULES\n",
            "1. Check if `tasks.md` needs to be updated (mark completed items with `[x]`). If so, WRITE IT FIRST.\n",
            "2. Check if `walkthrough.md` needs to be updated with new changes or verification results. If so, WRITE IT.\n",
            "3. Return commands in code blocks, e.g., ```bash\\ncat file.txt\\n```.\n",
            "4. For multi-line file creation, use heredocs: ```bash\\ncat << 'EOF' > filename.txt\\ncontent\\nEOF\\n```.\n",
            "5. If finished with the plan, return ```bash\\necho DONE\\n```.\n",
            "6. All commands are automatically sandboxed - unsafe paths will be blocked.\n",
            "7. Do not output multiple commands in one turn unless chained with `&&`.\n",
            "8. Wait for the result before proceeding.\n",
            "9. CRITICAL: Do NOT put commentary or explanations inside the code block. ONLY the command itself. Conversational text belongs outside the code block.\n",
            "10. NEVER use interactive tools (`nano`, `vim`, `less`).\n",
            "11. All commands are subject to sandbox validation and automatic timeouts.\n",
            "12. Use standard shell redirection for file operations.\n"
        ),
    },
    messages: MessageStrings {
        status_header: "**📊 System Status**\n\n",
        model_set: "✅ **Model set to**: `{}`",
        model_reset: "✅ **Model reset to default**.",
        invalid_model: "⚠️ **Invalid model index or name**.",
        no_projects_found: "📂 **No projects found**.",
        available_projects_header: "**📂 Available Projects**\n",
        invalid_project_name: "⚠️ **Invalid project name**.",
        admin_permission_denied: "{} you do not have permission to run terminal commands.",
        directory_changed: "📂 **Directory changed**: `{}`",
        access_denied_sandbox: "❌ Access denied: Path outside the sandbox.",
        directory_not_found: "❌ Directory not found.",
        command_no_output: "✅ (Command executed successfully, no output)",

        write_plan_error: "⚠️ Failed to write plan.md: {}",
        write_tasks_error: "⚠️ Failed to write tasks.md: {}",
        feedback_modification: "🔄 Modifying plan with feedback: *{FEEDBACK}*",
        failed_modify: "⚠️ **Failed to modify plan**:\n{}",
        plan_updated: "📜 **Plan Updated**:\n\n{}",
        limit_reached: "⚠️ **Limit Reached**: Stopped to prevent infinite loop.",
        stop_requested: "🛑 **Execution stopped by user.**",

        execution_complete: "🏁 **Execution Complete**\n\n{}{}\n### 📋 Result\n{}",
        agent_says: "🤔 **Agent says**:\n{}",
        agent_output: "✅ **Output**:\n```\n{}\n```",

        stop_request_wait: "🛑 **Stop requested**. Waiting for current step to finish...",
        plan_approved: "✅ Plan approved for: **{}**\nStarting interactive execution...",
        no_task_approve: "⚠️ **No task to approve**.",
        resuming_execution: "🔄 **Resuming execution**...",
        no_history_continue: "⚠️ **No execution history found to continue**. Start a new task.",

        please_commit_msg: "⚠️ **Please provide a commit message**: `.commit _message_`",
        committed_msg: "🚀 **Committed**:\n{}",
        changes_discarded: "🧹 **Changes discarded**.",
        checking_msg: "🔍 **Checking**...",
        check_result: "🔍 **Check Result**:\n{}",
        building_msg: "🔨 **Building**...",
        build_result: "🔨 **Build Result**:\n{}",
        deploying_msg: "🚀 **Deploying**...",
        deploy_result: "🚀 **Deploy Result**:\n{}",
        code_block_output: "```\n{}\n```",
        command_blocked: "Command '{}' is explicitly blocked. Please use a safer alternative (e.g., cat, ls, grep, echo).",
        command_ask: "Command '{}' requires confirmation.",
        command_not_allowed: "Command '{}' is not in allowlist.",
        command_unknown: "Unknown command '{}' (default policy is ask).",
        command_run_failed: "Failed to run command: {}",
        shell_command_failed: "Failed to run shell command: {}",
        command_approval_request: "⚠️ **Command requires confirmation**:\n`{}`\n\nType `.ok` to allow or `.no` to deny/skip.",
        command_denied_user: "🚫 **Command denied by user**.",
        no_pending_command: "⚠️ **No pending command to approve/deny**.",

        missing_env_var: "Missing env var {}",
        gemini_fetch_failed: "Failed to fetch Gemini models: {}",
        gemini_api_error: "Gemini API Error: {}",
        gemini_parse_error: "Failed to parse Gemini response: {}",
        anthropic_fetch_failed: "Failed to fetch Anthropic models: {}",
        anthropic_api_error: "Anthropic API Error: {}",
        anthropic_parse_error: "Failed to parse Anthropic response: {}",
        deepai_request_failed: "DeepAI Request Failed: {}",
        deepai_api_error: "DeepAI API Error: {}",
        deepai_parse_error: "DeepAI Parse Error: {}",
        unsupported_provider: "Unsupported Unified provider: {}",

        no_projects_configured: "⚠️ No `projects_dir` configured.",
        provide_project_name: "⚠️ **Please provide a project name**: `.new _name_`",
        project_exists: "📂 **Project already exists**. Switched to: `{}`\nSpecs detected.",
        create_dir_failed: "\n❌ **Failed to create directory** `{PATH}`: {ERR}",
        project_created: "\n📂 **Created and set project directory to**: `{}`\n📄 **Initialized specs**: `roadmap.md`, `changelog.md`",
        use_task_to_start: "\n\nUse `.task` to start a new workflow.",

        plan_generated: "### Plan\n\n{PLAN}\n\n### Tasks generated.{TASKS}\n",
        plan_generation_failed: "⚠️ **Failed to generate plan**:\n{}",
        no_active_task_modify: "⚠️ No active task to modify. Use `.task` first.",
        current_changes_header: "🔍 **Current Changes**:\n```diff\n{}\n```",
    },
    logs: LogStrings {
        config_loaded: "Loaded configuration for user: {}",
        login_success: "Logged in successfully!",
        setting_display_name: "Setting display name to: {}",
        set_display_name_fail: "Failed to set display name: {}",
        sync_loop_start: "Starting sync loop...",
        sync_loop_fail: "Sync loop failed: {}",
        shutdown: "Shutting down...",
        shutdown_fail: "Unable to listen for shutdown signal: {}",
        bridge_joining: "Bridge [{}]: Joining room {}...",
        bridge_join_fail: "   Failed to join room {}: {}",
        bridge_join_success: "   Successfully joined room {}.",
        invite_received: "💌 Received invite for room {:?}",
        join_invite_fail: "Failed to join room after invite: {}",
        join_invite_success: "✅ Successfully joined room!",
    },
};
